# Generated by Django 4.0.2 on 2025-11-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
